import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';
import { auth } from 'raiz/auth';
import { SessionProvider } from 'next-auth/react';
import { ProviderTanstack } from '../common/providers/ProviderTanstack';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<ProviderTanstack>{children}</ProviderTanstack>
				</body>
			</html>
		</SessionProvider>
	);
}
